{% set name = "dotnet-diagnostics" %}
{% set version = "8.0.532401" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/dotnet/diagnostics/archive/v{{ version }}.tar.gz
  sha256: 42f959934dacb0b72c6cef97e596e676858ec52c0ec9b8eed33761ca28ef8eeb

build:
  noarch: generic
  number: 0

requirements:
  build:
    - jq
  host:
    - dotnet
    - nuget-license
  run:
    - dotnet

test:
  commands:
    - dotnet-counters --help
    - dotnet-dsrouter --help
    - dotnet-dump --help
    - dotnet-gcdump --help
    - dotnet-sos --help
    - dotnet-stack --help
    - dotnet-trace --help

about:
  home: https://github.com/dotnet/diagnostics
  license: MIT
  license_file:
    - LICENSE.TXT
    - license-files/
  summary: .NET Core runtime diagnostic tools
  dev_url: https://github.com/dotnet/diagnostics

extra:
  recipe-maintainers:
    - danielnachun
