context:
  version: 7.0.410101

package:
  name: dotnet-diagnostics
  version: ${{ version }}

source:
  url: https://github.com/dotnet/diagnostics/archive/v${{ version }}.tar.gz
  sha256: bba2b1147614c61318bfb105481b28dae72491f0406932de714f2074871f40f6

build:
  number: 0
  noarch: generic

requirements:
  build:
    - jq
  host:
    - dotnet
    - nuget-license
  run:
    - dotnet

tests:
  - script:
      - dotnet-counters --help
      - dotnet-dsrouter --help
      - dotnet-dump --help
      - dotnet-gcdump --help
      - dotnet-sos --help
      - dotnet-stack --help
      - dotnet-trace --help

about:
  license: MIT
  license_file:
    - LICENSE.TXT
    - license-files/
  summary: .NET Core runtime diagnostic tools
  homepage: https://github.com/dotnet/diagnostics
  repository: https://github.com/dotnet/diagnostics

extra:
  recipe-maintainers:
    - danielnachun
