context:
  version: "9.0.652701"

package:
  name: dotnet-diagnostics
  version: ${{ version }}

source:
  url: https://github.com/dotnet/diagnostics/archive/v${{ version }}.tar.gz
  sha256: 22f18c57829dd0370d9db7eb240d354eeeb26964f3d8281a2f7f935742550b09

build:
  number: 0

requirements:
  build:
    - ${{ compiler('c') }}
    - ${{ compiler('cxx') }}
    - cmake
    - jq
    - sed
    - ninja
  host:
    - dotnet
    - lldb =18
    - nuget-license
  run:
    - dotnet

tests:
  - script:
      - dotnet-counters --help
      - dotnet-dsrouter --help
      - dotnet-dump --help
      - dotnet-gcdump --help
      - dotnet-sos --help
      - dotnet-stack --help
      - dotnet-trace --help

about:
  license: MIT
  license_file:
    - LICENSE.TXT
    - license-files/
  summary: .NET Core runtime diagnostic tools
  homepage: https://github.com/dotnet/diagnostics
  repository: https://github.com/dotnet/diagnostics

extra:
  recipe-maintainers:
    - danielnachun
